s3:
  main_raw_bucket: "s3a://main-raw-tick-data-bucket"
  test_raw_bucket: "s3a://test-raw-tick-data-bucket"
  main_clean_bucket: "s3a://main-clean-tick-data-bucket"
  test_clean_bucket: "s3a://test-clean-tick-data-bucket"